/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_scpi;

import java.awt.Color;

/**
 *
 * @author semfa
 */
public class Contact extends javax.swing.JFrame {

    /**
     * Creates new form Contact
     */
    public Contact() {
        initComponents();
        this.setLocationRelativeTo(null);
        lb_nom.setText(Connexion.name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnl_acceuil = new java.awt.Panel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnl_comprendre = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pnl_investir = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lb_souscription = new javax.swing.JLabel();
        lb_administration = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnl_contact = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lb_nom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_scpi/gauge-dashboard.png"))); // NOI18N
        jLabel3.setText("Dashboard");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        pnl_acceuil.setBackground(new java.awt.Color(0, 51, 102));
        pnl_acceuil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_acceuilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_acceuilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_acceuilMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_scpi/house-chimney-1.png"))); // NOI18N
        jLabel8.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Acceuil");
        jLabel9.setToolTipText("");

        javax.swing.GroupLayout pnl_acceuilLayout = new javax.swing.GroupLayout(pnl_acceuil);
        pnl_acceuil.setLayout(pnl_acceuilLayout);
        pnl_acceuilLayout.setHorizontalGroup(
            pnl_acceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_acceuilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(31, 31, 31)
                .addComponent(jLabel9)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        pnl_acceuilLayout.setVerticalGroup(
            pnl_acceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_acceuilLayout.createSequentialGroup()
                .addGroup(pnl_acceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel1.add(pnl_acceuil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 30));

        pnl_comprendre.setBackground(new java.awt.Color(0, 51, 102));
        pnl_comprendre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_comprendreMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Comprendre la SCPI");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_scpi/cog-double-3.png"))); // NOI18N
        jLabel19.setToolTipText("");

        javax.swing.GroupLayout pnl_comprendreLayout = new javax.swing.GroupLayout(pnl_comprendre);
        pnl_comprendre.setLayout(pnl_comprendreLayout);
        pnl_comprendreLayout.setHorizontalGroup(
            pnl_comprendreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_comprendreLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel19)
                .addGap(6, 6, 6)
                .addComponent(jLabel12))
        );
        pnl_comprendreLayout.setVerticalGroup(
            pnl_comprendreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_comprendreLayout.createSequentialGroup()
                .addGroup(pnl_comprendreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(6, 6, 6))
        );

        jPanel1.add(pnl_comprendre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, 30));

        pnl_investir.setBackground(new java.awt.Color(0, 51, 102));
        pnl_investir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_investirMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_scpi/analytics-graph-bar.png"))); // NOI18N
        jLabel16.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Investir en SCPI");

        javax.swing.GroupLayout pnl_investirLayout = new javax.swing.GroupLayout(pnl_investir);
        pnl_investir.setLayout(pnl_investirLayout);
        pnl_investirLayout.setHorizontalGroup(
            pnl_investirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_investirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_investirLayout.setVerticalGroup(
            pnl_investirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_investirLayout.createSequentialGroup()
                .addGroup(pnl_investirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel1.add(pnl_investir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 200, 30));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_scpi/search.png"))); // NOI18N

        lb_souscription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_souscription.setForeground(new java.awt.Color(255, 255, 255));
        lb_souscription.setText("Souscription");
        lb_souscription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_souscriptionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_souscriptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_souscriptionMouseExited(evt);
            }
        });

        lb_administration.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_administration.setForeground(new java.awt.Color(255, 255, 255));
        lb_administration.setText("Administrateur");
        lb_administration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_administrationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_administrationMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_scpi/logout-1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 169, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addComponent(lb_souscription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_administration, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_administration)
                                    .addComponent(lb_souscription))
                                .addGap(7, 7, 7))
                            .addComponent(jLabel1))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_scpi/Capture d’écran (677).png"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 600, 440));

        pnl_contact.setBackground(new java.awt.Color(0, 51, 102));
        pnl_contact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_contactMouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_scpi/headphones-customer-support-human-1.png"))); // NOI18N
        jLabel18.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Contacter-nous");

        javax.swing.GroupLayout pnl_contactLayout = new javax.swing.GroupLayout(pnl_contact);
        pnl_contact.setLayout(pnl_contactLayout);
        pnl_contactLayout.setHorizontalGroup(
            pnl_contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contactLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnl_contactLayout.setVerticalGroup(
            pnl_contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contactLayout.createSequentialGroup()
                .addGroup(pnl_contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel18))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel1.add(pnl_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 30));

        lb_nom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nom.setForeground(new java.awt.Color(255, 255, 255));
        lb_nom.setText("jLabel2");
        jPanel1.add(lb_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_acceuilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_acceuilMouseEntered
        // TODO add your handling code here:
        pnl_acceuil.setBackground(Color.black);
    }//GEN-LAST:event_pnl_acceuilMouseEntered

    private void pnl_acceuilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_acceuilMouseExited
        // TODO add your handling code here:
        pnl_acceuil.setBackground(Color.gray);
    }//GEN-LAST:event_pnl_acceuilMouseExited

    private void lb_souscriptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_souscriptionMouseEntered
        // TODO add your handling code here:
        lb_souscription.setForeground(Color.red);
    }//GEN-LAST:event_lb_souscriptionMouseEntered

    private void lb_souscriptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_souscriptionMouseExited
        // TODO add your handling code here:
        lb_souscription.setForeground(Color.white);
    }//GEN-LAST:event_lb_souscriptionMouseExited

    private void lb_administrationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_administrationMouseEntered
        // TODO add your handling code here:
        lb_administration.setForeground(Color.red);
    }//GEN-LAST:event_lb_administrationMouseEntered

    private void lb_administrationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_administrationMouseExited
        // TODO add your handling code here:
        lb_administration.setForeground(Color.white);
    }//GEN-LAST:event_lb_administrationMouseExited

    private void pnl_acceuilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_acceuilMouseClicked
        // TODO add your handling code here:
        Acceuil1 frame = new Acceuil1();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_pnl_acceuilMouseClicked

    private void pnl_comprendreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_comprendreMouseClicked
        // TODO add your handling code here:
        Comprendre frame = new Comprendre();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_pnl_comprendreMouseClicked

    private void pnl_investirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_investirMouseClicked
        // TODO add your handling code here:
        Investir frame = new Investir();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_pnl_investirMouseClicked

    private void pnl_contactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_contactMouseClicked
        // TODO add your handling code here:
        Contact frame = new Contact();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_pnl_contactMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Connexion frame = new Connexion();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void lb_souscriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_souscriptionMouseClicked
        // TODO add your handling code here:
        souscription frame = new souscription();
        frame.setVisible(true);
        
    }//GEN-LAST:event_lb_souscriptionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lb_administration;
    private javax.swing.JLabel lb_nom;
    private javax.swing.JLabel lb_souscription;
    private java.awt.Panel pnl_acceuil;
    private javax.swing.JPanel pnl_comprendre;
    private javax.swing.JPanel pnl_contact;
    private javax.swing.JPanel pnl_investir;
    // End of variables declaration//GEN-END:variables
}
