/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interface_scpi;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static signature.UniversignRPCRequest.loadDoc;

/**
 *
 * @author semfa
 */
public class signature_frame extends javax.swing.JFrame {

    /** Creates new form signature_frame */
    
    public signature_frame() {
        initComponents();
        //lb_lien_signature.setText(signature.UniversignRPCRequest.doRequest.res.get("url")));
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        obtenir_lien_tb = new javax.swing.JButton();
        tb_lien = new javax.swing.JTextField();
        page_web_direct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Liens vers le telechargement du pdf");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Copier ce lien dans votre navigateur et tapez le code qui vous sera envoye par message pour signer votre pdf");

        jButton1.setText("Terminer");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        obtenir_lien_tb.setText("Obtenir le lien");
        obtenir_lien_tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                obtenir_lien_tbMouseClicked(evt);
            }
        });

        tb_lien.setForeground(new java.awt.Color(102, 255, 102));

        page_web_direct.setText("Aller sur la page pour signer");
        page_web_direct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                page_web_directMouseClicked(evt);
            }
        });
        page_web_direct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page_web_directActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tb_lien, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(page_web_direct)
                                .addGap(18, 18, 18)
                                .addComponent(obtenir_lien_tb)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(62, 62, 62)
                .addComponent(tb_lien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(page_web_direct)
                    .addComponent(obtenir_lien_tb))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Acceuil1 frame = new Acceuil1();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void obtenir_lien_tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_obtenir_lien_tbMouseClicked
        try {
            // TODO add your handling code here:
            String lien = signature.UniversignRPCRequest.doRequest("semfanou@gmail.com", "selorD07-", loadDoc()).toString(); //recuperation du url de la page de signature dans la variable lien
            //lb_lien_signature.setText(lien);
            tb_lien.setText(lien); //envoie du lien dans le tb_lien
            
        } catch (IOException ex) {
            Logger.getLogger(signature_frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_obtenir_lien_tbMouseClicked

    private void page_web_directActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page_web_directActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_page_web_directActionPerformed

    private void page_web_directMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_page_web_directMouseClicked
        //ouvrir la page de signature directement dans le navigateur
            String url;
        try {
            url = signature.UniversignRPCRequest.doRequest("semfanou@gmail.com", "selorD07-", loadDoc()).toString();
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (IOException ex) {
            Logger.getLogger(signature_frame.class.getName()).log(Level.SEVERE, null, ex);
        }
;
            
        
    }//GEN-LAST:event_page_web_directMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signature_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signature_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signature_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signature_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signature_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton obtenir_lien_tb;
    private javax.swing.JButton page_web_direct;
    private javax.swing.JTextField tb_lien;
    // End of variables declaration//GEN-END:variables

}
