/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_scpi;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import static interface_scpi.souscription.nom_pdf;
import java.io.FileOutputStream;

/**
 *
 * @author semfa
 */
public class souscription1 extends javax.swing.JFrame {

    /**
     * Creates new form souscription1
     */
    String personne;
    public souscription1() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tb_adresse = new javax.swing.JTextField();
        cb_investir = new javax.swing.JComboBox<>();
        cb_proprietaire = new javax.swing.JComboBox<>();
        cb_activite = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cb_objectif = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cb_duree = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        rb_physique = new javax.swing.JRadioButton();
        rb_moral = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        tb_postal = new javax.swing.JTextField();
        tb_ville = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tb_pays = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Adresse");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Proprietaire");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Activité");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Investissement");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, 20));
        jPanel1.add(tb_adresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 147, -1));

        cb_investir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "En demembrement", "En assurance-vie", "Credit", "Je ne sais pas", " " }));
        jPanel1.add(cb_investir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 140, -1));

        cb_proprietaire.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oui", "Non" }));
        cb_proprietaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_proprietaireActionPerformed(evt);
            }
        });
        jPanel1.add(cb_proprietaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 147, -1));

        cb_activite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salarié", "Independant / Chef d'entreprise", "Retraité", "Au chomage / Sans activité", "Etudiant", " " }));
        cb_activite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_activiteActionPerformed(evt);
            }
        });
        jPanel1.add(cb_activite, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 147, -1));

        jButton1.setText("Suivant");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 320, -1, -1));

        jButton2.setText("Precedant");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, -1, -1));

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getStyle() | java.awt.Font.BOLD, jLabel6.getFont().getSize()+3));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Objectif");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        cb_objectif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prpearer ma retraite", "Avoir un meilleure rendement de mon epargne", "Diversifier mon patrimoine", "Créer du capital", " " }));
        jPanel1.add(cb_objectif, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 140, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Durée");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        cb_duree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4 ans", "Entre 4 - 8 ans", "Entre 8 - 12 ans", ">12ans", "Je ne sais pas", " " }));
        jPanel1.add(cb_duree, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 147, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Etes-vous une personne physique ou moral");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        rb_physique.setText("Personne physique");
        rb_physique.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_physiqueMouseClicked(evt);
            }
        });
        rb_physique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_physiqueActionPerformed(evt);
            }
        });
        jPanel1.add(rb_physique, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        rb_moral.setText("Personne moral");
        rb_moral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_moralMouseClicked(evt);
            }
        });
        jPanel1.add(rb_moral, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Code postal");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        tb_postal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_postalActionPerformed(evt);
            }
        });
        jPanel1.add(tb_postal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 140, -1));
        jPanel1.add(tb_ville, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 147, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ville");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Pays");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));
        jPanel1.add(tb_pays, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 147, -1));

        jButton4.setText("Cancel");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 80, -1));

        jButton3.setText("Cancel");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_proprietaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_proprietaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_proprietaireActionPerformed

    private void cb_activiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_activiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_activiteActionPerformed

    private void rb_physiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_physiqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_physiqueActionPerformed

    private void tb_postalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_postalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_postalActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        souscription frame = new souscription();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try{
            /*com.itextpdf.text.Document document = new com.itextpdf.text.Document();
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("C:\\Users\\semfa\\"+ souscription.nom_pdf+".pdf"));
            */
            //souscription.document.open();
            //ecriture dans le pdf ouvert sur la fentetre souscription.java
            souscription.document.add(new Paragraph("Statu de la personne: "+personne+ "\n"
                                        +"Adresse: "+ tb_adresse.getText()+"\n"
                                        +"Ville: "+ tb_ville.getText()+"\n"
                                        +"Pays: "+ tb_pays.getText()+ "\n"
                                        +"Code postal: "+ tb_postal.getText()+"\n"
                                        +"Proprietaire: "+ cb_proprietaire.getSelectedItem().toString()+"\n"
                                        +"Activite: "+ cb_activite.getSelectedItem().toString()+"\n"
                                        +"Duree: "+ cb_duree.getSelectedItem().toString()+"\n"
                                        +"Type d'investissement: "+ cb_investir.getSelectedItem().toString()+"\n"
                                        +"Objectif de votre epargne: "+ cb_objectif.getSelectedItem().toString()));
            //souscription.document.close();
            //pas de fermeture parceque reste encore des elements a ajouter sur les autres fenetres
            
        }catch(Exception e){
            System.out.println(e);
        }
        fonctions.insert_souscription1(personne, tb_adresse.getText(), tb_ville.getText(), cb_proprietaire.getSelectedItem().toString(), cb_activite.getSelectedItem().toString(), cb_duree.getSelectedItem().toString(),
        tb_pays.getText(), tb_postal.getText(), cb_investir.getSelectedItem().toString(), cb_objectif.getSelectedItem().toString()); //insertion des donnée recueperer dans le fichier souscription.xml dans la balise page1
        
        souscription2 frame = new souscription2();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void rb_physiqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_physiqueMouseClicked

        rb_moral.setSelected(false);
        personne = "physique";
    }//GEN-LAST:event_rb_physiqueMouseClicked

    private void rb_moralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_moralMouseClicked
        // TODO add your handling code here:
        rb_physique.setSelected(false);
        personne = "morale";
    }//GEN-LAST:event_rb_moralMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(souscription1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(souscription1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(souscription1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(souscription1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new souscription1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_activite;
    private javax.swing.JComboBox<String> cb_duree;
    private javax.swing.JComboBox<String> cb_investir;
    private javax.swing.JComboBox<String> cb_objectif;
    private javax.swing.JComboBox<String> cb_proprietaire;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rb_moral;
    private javax.swing.JRadioButton rb_physique;
    private javax.swing.JTextField tb_adresse;
    private javax.swing.JTextField tb_pays;
    private javax.swing.JTextField tb_postal;
    private javax.swing.JTextField tb_ville;
    // End of variables declaration//GEN-END:variables
}
