/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_scpi;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import static interface_scpi.souscription.document;
import java.io.FileOutputStream;
import static java.nio.file.StandardOpenOption.APPEND;
import org.w3c.dom.Document;

/**
 *
 * @author semfa
 */
public class souscription extends javax.swing.JFrame {

    /**
     * Creates new form souscription
     */
    public static String nom_pdf; //declaration global du la variable nom_pdf = nom du pdf a telecharger
    public static com.itextpdf.text.Document document = new com.itextpdf.text.Document(); //declaration global de creation d'un document avec la bibliotheque itext
    //PdfWriter.getInstance(document, new FileOutputStream("C:\\Users\\semfa\\"+ nom_pdf+".pdf"));
    
    public souscription() {
        initComponents();
        this.setLocationRelativeTo(null);
        //nom_pdf = tb_nom.getText()+"_"+tb_prenom.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tb_nom = new javax.swing.JTextField();
        tb_prenom = new javax.swing.JTextField();
        tb_telephone = new javax.swing.JTextField();
        tb_email = new javax.swing.JTextField();
        tb_enfant = new javax.swing.JTextField();
        cb_matrimoniale = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nom");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 57, 36));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prenom");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 70, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Situation Matrimonial");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telephone");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 19));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 50, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enfant");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 50, -1));
        jPanel2.add(tb_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 140, 20));

        tb_prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_prenomActionPerformed(evt);
            }
        });
        jPanel2.add(tb_prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 130, -1));
        jPanel2.add(tb_telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 140, -1));
        jPanel2.add(tb_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 130, -1));
        jPanel2.add(tb_enfant, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 130, -1));

        cb_matrimoniale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Célibataire", "Concubinage", "Marié(e)", "Divorcé", "Veuf(ve)" }));
        jPanel2.add(cb_matrimoniale, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 140, -1));

        jButton2.setText("Suivant");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        jButton1.setText("Cancel");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_prenomActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        nom_pdf = tb_nom.getText()+"_"+tb_prenom.getText(); //attribution du nom du pdf en concatenant les text ecrit dans le tb_nom et tb_prenom
        try{
            //com.itextpdf.text.Document document = new com.itextpdf.text.Document();
            PdfWriter.getInstance(document, new FileOutputStream("C:\\Users\\semfa\\"+ nom_pdf+".pdf"));//creation du document en mode ecriture
            
            document.open(); //ouverture du document et ajout des differant valeur saisir dans le pdf  
            document.add(new Paragraph("Nom: "+tb_nom.getText()+ "\n"
                                        +"Prenom: "+ tb_prenom.getText()+"\n"
                                        +"Email: "+ tb_email.getText()+"\n"
                                        +"Nombre d'enfant: "+ tb_enfant.getText()+ "\n"
                                        +"Numero de telephone: "+ tb_telephone.getText()+"\n"
                                        +"Situation matrimoniale"+ cb_matrimoniale.getSelectedItem().toString()));
            //document.close();
            //pas de fermeture pour pouvoir continuer a ecrire dans le pdf dans les autre fenetre
            
        }catch(Exception e){
            System.out.println(e);
        }
       
        fonctions.insert_souscription(tb_nom.getText(), tb_prenom.getText(), tb_enfant.getText(), tb_email.getText(), tb_telephone.getText(), cb_matrimoniale.getSelectedItem().toString());//insertion des donnée recuperer sur l'interface dans le fichier xml souscription.xml dans la balise page0
        souscription1 frame = new souscription1();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(souscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(souscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(souscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(souscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new souscription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_matrimoniale;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tb_email;
    private javax.swing.JTextField tb_enfant;
    private javax.swing.JTextField tb_nom;
    private javax.swing.JTextField tb_prenom;
    private javax.swing.JTextField tb_telephone;
    // End of variables declaration//GEN-END:variables
}
