/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_scpi;

import com.itextpdf.text.Paragraph;

/**
 *
 * @author semfa
 */
public class souscription3 extends javax.swing.JFrame {

    /**
     * Creates new form souscription3
     */
    String capital, baisse, variation, limite; //declaration des variable pour les valeur pouvant recuperer a chaque bouton radio choisir
    public souscription3() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tb_nbr_transaction = new javax.swing.JTextField();
        cb_transaction = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        cb_investir = new javax.swing.JComboBox<>();
        cb_paiement = new javax.swing.JComboBox<>();
        cb_provenance = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rb_capital_oui = new javax.swing.JRadioButton();
        rb_capital_non = new javax.swing.JRadioButton();
        rb_baisse_oui = new javax.swing.JRadioButton();
        rb_baisse_non = new javax.swing.JRadioButton();
        rb_limite_oui = new javax.swing.JRadioButton();
        rb_limite_non = new javax.swing.JRadioButton();
        rb_variation_non = new javax.swing.JRadioButton();
        rb_variation_oui = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fréquence de transaction");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 180, 36));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre de transaction");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 160, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Acceptez-vous ce risque en capital");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 240, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Type de paiement");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 19));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Provenance des fonds");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 160, -1));

        tb_nbr_transaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_nbr_transactionActionPerformed(evt);
            }
        });
        jPanel2.add(tb_nbr_transaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 130, -1));

        cb_transaction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mensuelle", "Trimestrielle", "Annuellle", "Superieur a 1 an", "Aucune" }));
        jPanel2.add(cb_transaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 140, 20));

        jButton2.setText("Suivant");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 80, -1));

        cb_investir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moins de 15000€", "Entre 15 000€ et 30 000€", "Entre 30 000€ et 50 000€", "Entre 50 000€ et 100 000€", "Plus de 100 000€" }));
        jPanel2.add(cb_investir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 200, -1));

        cb_paiement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Par le souscripteur", "Par un tier" }));
        jPanel2.add(cb_paiement, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 140, -1));

        cb_provenance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "France", "Union Européene", "Autre", " " }));
        jPanel2.add(cb_provenance, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 130, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Etes-vous pret a prendre le risque de la variation a la baisse des revenues");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 510, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Acceptez-vous de prendre un risque lié a la variation du cout");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 440, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Combien souhaitez vous investir sur les 12 ans");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 320, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Acceptez-vous que la liquidité de vos part puisse etre limité");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 410, -1));

        rb_capital_oui.setText("Oui");
        rb_capital_oui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_capital_ouiMouseClicked(evt);
            }
        });
        jPanel2.add(rb_capital_oui, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, -1));

        rb_capital_non.setText("Non");
        rb_capital_non.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_capital_nonMouseClicked(evt);
            }
        });
        jPanel2.add(rb_capital_non, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, -1, -1));

        rb_baisse_oui.setText("Oui");
        rb_baisse_oui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_baisse_ouiMouseClicked(evt);
            }
        });
        jPanel2.add(rb_baisse_oui, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, -1));

        rb_baisse_non.setText("Non");
        rb_baisse_non.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_baisse_nonMouseClicked(evt);
            }
        });
        jPanel2.add(rb_baisse_non, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, -1, -1));

        rb_limite_oui.setText("Oui");
        rb_limite_oui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_limite_ouiMouseClicked(evt);
            }
        });
        jPanel2.add(rb_limite_oui, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        rb_limite_non.setText("Non");
        rb_limite_non.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_limite_nonMouseClicked(evt);
            }
        });
        jPanel2.add(rb_limite_non, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, -1, -1));

        rb_variation_non.setText("Non");
        rb_variation_non.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_variation_nonMouseClicked(evt);
            }
        });
        jPanel2.add(rb_variation_non, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, -1, -1));

        rb_variation_oui.setText("Oui");
        rb_variation_oui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_variation_ouiMouseClicked(evt);
            }
        });
        jPanel2.add(rb_variation_oui, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        jButton3.setText("Precedant");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        jButton1.setText("Cancel");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        try{
            /*com.itextpdf.text.Document document = new com.itextpdf.text.Document();
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("C:\\Users\\semfa\\"+ souscription.nom_pdf+".pdf"));
            */
            //souscription.document.open();
            souscription.document.add(new Paragraph("Etes-vous pret a prendre le risque de la variation a la baisse des revenues: "+baisse+ "\n"
                                        +"Acceptez-vous que la liquidité de vos part puisse etre limité: "+ limite+"\n"
                                        +"Acceptez-vous de prendre un risque lié a la variation du cout: "+ variation+"\n"
                                        +"Nombre de transaction: "+ tb_nbr_transaction.getText()+ "\n"
                                        
                                        +"Frequence de transaction: "+ cb_transaction.getSelectedItem().toString()+"\n"
                                        +"Investissement sur les 12mois: "+ cb_investir.getSelectedItem().toString()+"\n"
                                        +"Type de paiement: "+ cb_paiement.getSelectedItem().toString()+"\n"
                                        +"Provenance du financement: "+ cb_provenance.getSelectedItem().toString()+"\n"
                                        +"Acceptez-vous ce risque en capital: "+ capital));
            //souscription.document.close();
            
        }catch(Exception e){
            System.out.println(e);
        }
        fonctions.insert_souscription3(cb_transaction.getSelectedItem().toString(), tb_nbr_transaction.getText(),
                cb_investir.getSelectedItem().toString(), cb_paiement.getSelectedItem().toString(), cb_provenance.getSelectedItem().toString(),
                capital, baisse, limite, variation);
        souscription41 frame = new souscription41();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tb_nbr_transactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_nbr_transactionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_nbr_transactionActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        souscription2 frame = new souscription2();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void rb_capital_ouiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_capital_ouiMouseClicked
        // TODO add your handling code here:
        rb_capital_non.setSelected(false);
        capital = "oui";
    }//GEN-LAST:event_rb_capital_ouiMouseClicked

    private void rb_capital_nonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_capital_nonMouseClicked
        // TODO add your handling code here:
        rb_capital_oui.setSelected(false);
        capital = "non";
    }//GEN-LAST:event_rb_capital_nonMouseClicked

    private void rb_baisse_ouiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_baisse_ouiMouseClicked
        // TODO add your handling code here:
        rb_baisse_non.setSelected(false);
        baisse = "oui";
    }//GEN-LAST:event_rb_baisse_ouiMouseClicked

    private void rb_baisse_nonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_baisse_nonMouseClicked
        // TODO add your handling code here:
        rb_baisse_oui.setSelected(false);
        baisse = "non";
    }//GEN-LAST:event_rb_baisse_nonMouseClicked

    private void rb_limite_ouiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_limite_ouiMouseClicked
        // TODO add your handling code here:
        rb_limite_non.setSelected(false);
        limite = "oui";
    }//GEN-LAST:event_rb_limite_ouiMouseClicked

    private void rb_limite_nonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_limite_nonMouseClicked
        // TODO add your handling code here:
        rb_limite_oui.setSelected(false);
        limite = "non";
    }//GEN-LAST:event_rb_limite_nonMouseClicked

    private void rb_variation_ouiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_variation_ouiMouseClicked
        // TODO add your handling code here:
        rb_variation_non.setSelected(false);
        variation = "oui";
    }//GEN-LAST:event_rb_variation_ouiMouseClicked

    private void rb_variation_nonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_variation_nonMouseClicked
        // TODO add your handling code here:
        rb_variation_oui.setSelected(false);
        variation = "non";
    }//GEN-LAST:event_rb_variation_nonMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(souscription3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(souscription3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(souscription3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(souscription3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new souscription3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_investir;
    private javax.swing.JComboBox<String> cb_paiement;
    private javax.swing.JComboBox<String> cb_provenance;
    private javax.swing.JComboBox<String> cb_transaction;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rb_baisse_non;
    private javax.swing.JRadioButton rb_baisse_oui;
    private javax.swing.JRadioButton rb_capital_non;
    private javax.swing.JRadioButton rb_capital_oui;
    private javax.swing.JRadioButton rb_limite_non;
    private javax.swing.JRadioButton rb_limite_oui;
    private javax.swing.JRadioButton rb_variation_non;
    private javax.swing.JRadioButton rb_variation_oui;
    private javax.swing.JTextField tb_nbr_transaction;
    // End of variables declaration//GEN-END:variables
}
