/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_scpi;

import com.itextpdf.text.Paragraph;

/**
 *
 * @author semfa
 */
public class souscription2 extends javax.swing.JFrame {

    /**
     * Creates new form souscription2
     */
    String charge, politique, us; //declaration des variable pour les valeur pouvant recuperer a chaque bouton radio choisir
    public souscription2() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tb_nationalite = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tb_pays_naissance = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tb_date_naissance = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tb_ville_naissance = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rb_politique_oui = new javax.swing.JRadioButton();
        rb_politique_non = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rb_us_oui = new javax.swing.JRadioButton();
        rb_us_non = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        tb_montant = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cb_revenu = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cb_patrimonial = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        rb_charge_oui = new javax.swing.JRadioButton();
        rb_charge_non = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nationalité");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        jPanel1.add(tb_nationalite, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 147, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pays de naissance");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));
        jPanel1.add(tb_pays_naissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 147, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("US person");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));
        jPanel1.add(tb_date_naissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 147, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ville de naissance");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));
        jPanel1.add(tb_ville_naissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 147, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date de naissance");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        rb_politique_oui.setText("Oui");
        rb_politique_oui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_politique_ouiMouseClicked(evt);
            }
        });
        rb_politique_oui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_politique_ouiActionPerformed(evt);
            }
        });
        jPanel1.add(rb_politique_oui, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        rb_politique_non.setText("Non");
        rb_politique_non.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_politique_nonMouseClicked(evt);
            }
        });
        jPanel1.add(rb_politique_non, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Personne politiquement exposé");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        rb_us_oui.setText("Oui");
        rb_us_oui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_us_ouiMouseClicked(evt);
            }
        });
        rb_us_oui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_us_ouiActionPerformed(evt);
            }
        });
        jPanel1.add(rb_us_oui, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        rb_us_non.setText("Non");
        rb_us_non.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_us_nonMouseClicked(evt);
            }
        });
        jPanel1.add(rb_us_non, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Montant de loyer");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        jPanel1.add(tb_montant, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 147, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Situation patrimonial");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        cb_revenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moins de 30000€", "Entre 30000€ et 50000€", "Entre 50000€ et 100000€", "Entre 100000€ et 500000€", "Plus de 500000€", " " }));
        jPanel1.add(cb_revenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Autres charges");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        cb_patrimonial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moins de 50000€", "Entre 50000€ et 100000€", "Entre 100000€ et 500000€", "Entre 500000€ et 1000000€", "Plus de 1000000€" }));
        jPanel1.add(cb_patrimonial, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 150, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Revenue annuels net");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        rb_charge_oui.setText("Oui");
        rb_charge_oui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_charge_ouiMouseClicked(evt);
            }
        });
        jPanel1.add(rb_charge_oui, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));

        rb_charge_non.setText("Non");
        rb_charge_non.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_charge_nonMouseClicked(evt);
            }
        });
        jPanel1.add(rb_charge_non, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, -1, -1));

        jButton2.setText("Precedant");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, -1, -1));

        jButton1.setText("Suivant");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 320, -1, -1));

        jButton3.setText("Cancel");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_politique_ouiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_politique_ouiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_politique_ouiActionPerformed

    private void rb_us_ouiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_us_ouiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_us_ouiActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        souscription1 frame = new souscription1();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try{
            /*com.itextpdf.text.Document document = new com.itextpdf.text.Document();
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("C:\\Users\\semfa\\"+ souscription.nom_pdf+".pdf"));
            */
            //souscription.document.open();
            //ecriture dans le pdf ouvert sur la fentetre souscription.java
            souscription.document.add(new Paragraph("Nationalite: "+tb_nationalite.getText()+ "\n"
                                        +"Date de naissance: "+ tb_date_naissance.getText()+"\n"
                                        +"Montant de loyer: "+ tb_montant.getText()+"\n"
                                        +"Pays de naissance: "+ tb_pays_naissance.getText()+ "\n"
                                        +"Ville de naissance: "+ tb_ville_naissance.getText()+"\n"
                                        +"Revenue annuel net: "+ cb_revenu.getSelectedItem().toString()+"\n"
                                        +"Situation patrimoniale: "+ cb_patrimonial.getSelectedItem().toString()+"\n"
                                        +"Autre charges(pension alimentaire etc..): "+ charge+"\n"
                                        +"Personne politiquement expose: "+ politique+"\n"
                                        +"Us person: "+ us));
            //souscription.document.close();
            //pas de fermeture parceque reste encore des elements a ajouter sur les autres fenetres
            
        }catch(Exception e){
            System.out.println(e);
        }
        fonctions.insert_souscription2(tb_nationalite.getText(), tb_date_naissance.getText(), tb_montant.getText(), cb_revenu.getSelectedItem().toString(),
                tb_pays_naissance.getText(), tb_ville_naissance.getText(), cb_patrimonial.getSelectedItem().toString(), charge, politique, us);
        souscription3 frame = new souscription3();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void rb_charge_ouiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_charge_ouiMouseClicked
        // TODO add your handling code here:
        rb_charge_non.setSelected(false);
        charge = "oui";
    }//GEN-LAST:event_rb_charge_ouiMouseClicked

    private void rb_charge_nonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_charge_nonMouseClicked
        // TODO add your handling code here:
        rb_charge_oui.setSelected(false);
        charge = "non";
    }//GEN-LAST:event_rb_charge_nonMouseClicked

    private void rb_politique_ouiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_politique_ouiMouseClicked
        // TODO add your handling code here:
        rb_politique_non.setSelected(false);
        politique = "oui";
    }//GEN-LAST:event_rb_politique_ouiMouseClicked

    private void rb_politique_nonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_politique_nonMouseClicked
        // TODO add your handling code here:
        rb_politique_oui.setSelected(false);
        politique = "non";
    }//GEN-LAST:event_rb_politique_nonMouseClicked

    private void rb_us_ouiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_us_ouiMouseClicked
        // TODO add your handling code here:
        rb_us_non.setSelected(false);
        us = "oui";
    }//GEN-LAST:event_rb_us_ouiMouseClicked

    private void rb_us_nonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_us_nonMouseClicked
        // TODO add your handling code here:
        rb_us_oui.setSelected(false);
        us = "non";
    }//GEN-LAST:event_rb_us_nonMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(souscription2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(souscription2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(souscription2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(souscription2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new souscription2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_patrimonial;
    private javax.swing.JComboBox<String> cb_revenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rb_charge_non;
    private javax.swing.JRadioButton rb_charge_oui;
    private javax.swing.JRadioButton rb_politique_non;
    private javax.swing.JRadioButton rb_politique_oui;
    private javax.swing.JRadioButton rb_us_non;
    private javax.swing.JRadioButton rb_us_oui;
    private javax.swing.JTextField tb_date_naissance;
    private javax.swing.JTextField tb_montant;
    private javax.swing.JTextField tb_nationalite;
    private javax.swing.JTextField tb_pays_naissance;
    private javax.swing.JTextField tb_ville_naissance;
    // End of variables declaration//GEN-END:variables
}
